### ISSUE TITLE
Few requests for experiments and citation

### ISSUE THREAD

**Issue by Jaewon040** [LukasHaas/PIGEON#1]
Hello. Thank you for your excellent work. I've been trying to cite your paper after conducting a few validations, but it seems the weights are not available, making it difficult to proceed. Could you please upload them? Additionally, I'm having trouble running the 'run.py' file because I can't locate the 'multiprocess.py' file. Would you be able to upload it as well?

**Comment by LukasHaas** [comment]
Hi, thanks for your feedback. In the run.py file, the module to import should be Python‘s native `multiprocessing`library. I corrected the name in run.py.

Regarding the model weights, we have decided not to make them publicly available for safety reasons. Our paper contains more information about this decision.

**Comment by Jaewon040** [comment]
Okay i respect your decision! 
Thank you
