### ISSUE TITLE
How to get admin_2.geojson？

### ISSUE THREAD

**Issue by yingjun-zhang** [LukasHaas/PIGEON#4]
Hi! Thank you and your amazing work. 
When I want to run geocell_creation.py, I get an error: fiona._err.CPLE_OpenFailedError: data/geocells/admin_2.geojson: No such file or directory
Could you please explain how to get this file？

**Comment by yingjun-zhang** [comment]
country, admin 1, and admin 2 levels) obtained from GADM [10]

**Comment by yingjun-zhang** [comment]
country, admin 1, and admin 2 levels) obtained from GADM [10]

**Comment by uloma07** [comment]
@yingjun-zhang Please can you explain how you obtained them from GADM?

**Comment by yunusserhat** [comment]
> @yingjun-zhang Please can you explain how you obtained them from GADM?


Could you try this; https://gadm.org/download_world.html

**Comment by uloma07** [comment]
Hi @yunusserhat, thanks for the link.
I had checked the GADM website before I asked. As far as I can see I can download the data as a geopackage consisting of different layers. I guess my real question is how do you go from the geopackage to the .geojson file for specific layers i.e ADMIN_1, ADMIN_2, and Countries(ADMIN_0)?

Thanks again
